---
- name: install and configure the shoppingListBot app
  hosts: 'shoppingBot'

  vars:
    appFile : 'shoppingListBot.zip'

  tasks:
    - name: "include vault variables"
      include_vars: "vault.yml"

    - name: "Zip up the application directory"
      archive:
        path: "../app"
        dest: "shoppingListBot.tgz"
      delegate_to: localhost

    - name: "Create /apps directory"
      file:
        path: /apps
        state: directory
        owner: heidi
        group: heidi
      become: yes

    - name: "Unarchive shoppingListBot.tgz"
      unarchive:
        src: "shoppingListBot.tgz"
        dest: "/apps/"
        owner: heidi
        group: heidi

    - name: Install node.js if not present
      become: yes
      apt:
        name: nodejs
        state: latest

    - name: Install NPM packages based on package.json.
      npm:
        path: /apps/app/

    - name: "Install forever (to run Node.js app)."
      become: yes
      npm:
        name: forever
        global: yes
        state: present

    - name: "Check list of Node.js apps running."
      command: forever list
      register: forever_list
      changed_when: false

    - name: "Restart app."
      command: "forever restart /apps/app/app.js --workingDir=/apps/app/"
      environment:
        CLIENT_SIGNING_SECRET: "{{SLACK_CLIENT_SIGNING_SECRET}}"
        BOT_TOKEN: "{{SLACK_BOT_TOKEN}}"
        SLACK_GEN_CHANNEL: "{{SLACK_GEN_CHANNEL}}"
      when: "forever_list.stdout.find('/apps/app/app.js') != -1"

    - name: "Start app."
      command: "forever start /apps/app/app.js --workingDir=/apps/app/"
      environment:
        CLIENT_SIGNING_SECRET: "{{SLACK_CLIENT_SIGNING_SECRET}}"
        BOT_TOKEN: "{{SLACK_BOT_TOKEN}}"
        SLACK_GEN_CHANNEL: "{{SLACK_GEN_CHANNEL}}"
      when: "forever_list.stdout.find('/apps/app/app.js') == -1"